[tool.poetry]
package-mode = false
name = "aggregator"
version = "0.1.0"
description = "This component consumes Anomalies from Valkey, save videos and sends reporting data to receivers like ai-cockpit."
authors = ["witchpou <anett.huebner@starwit.de>"]
license = "AGPLv3"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pydantic = "^2.10.6"
visionapi = { git = "https://github.com/starwit/vision-api.git", subdirectory = "python/visionapi", tag = "3.2.1" }
redis = "^6.2.0"
pydantic-settings = "^2.8.1"
prometheus-client = "^0.22.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
