#!/bin/bash
set -e

# Create 
if [ "$1" = "configure" ]; then

    cd "/opt/starwit/detection-aggregator"
    python3 -m venv .venv
    source .venv/bin/activate
    pip install -r requirements.txt    

    echo "Create wrapper script"
    mkdir -p /usr/local/bin
    cat > /usr/local/bin/detection-aggregator <<EOF
#!/bin/bash

current_dir=$PWD
cd /opt/starwit/detection-aggregator
source .venv/bin/activate

python3 main.py "\$@"
cd $current_dir
EOF
    chmod +x /usr/local/bin/detection-aggregator    

    # link settings file from etc
    cd /opt/starwit/detection-aggregator
    ln -sf /etc/starwit/detection-aggregator/settings.yaml settings.yaml

    systemctl daemon-reload
    systemctl start detection-aggregator.service        
    systemctl enable detection-aggregator.service
fi

#DEBHELPER#

exit 0