#!/bin/bash
set -e

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then

    # Stop the service
    systemctl stop detection-aggregator.service

    # Disable the service
    systemctl disable detection-aggregator.service

    # Remove the service file
    rm -f /etc/systemd/system/detection-aggregator.service

    systemctl daemon-reload

    # Remove the wrapper script
    rm -f /usr/local/bin/detection-aggregator
    
    # Remove application directory
    rm -rf /opt/starwit/detection-aggregator

    # Remove config files directory
    rm -rf /etc/starwit/detection-aggregator
fi

#DEBHELPER#

exit 0